# Generated by Django 4.2 on 2023-05-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('valor', models.FloatField()),
                ('descricao', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.TextField()),
                ('caminho', models.CharField(max_length=100)),
                ('total', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.TextField()),
                ('caminho', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.cardapio')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.comanda')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.mesa')),
            ],
        ),
    ]
