# Generated by Django 4.2 on 2023-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='caminho',
            field=models.TextField(max_length=100, null=100),
            preserve_default=100,
        ),
    ]
